apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
    name: redash-provisioner-role
    namespace: {{ .Release.Namespace }}
rules:
    - apiGroups: [""]
      resources: ["secrets"]
      resourceNames: ["redash-secrets"]
      verbs: ["create","get","patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    name: redash-provisioner-role-binding
    namespace: {{ .Release.Namespace }}
subjects:
 - kind: ServiceAccount
   name: redash-provisioner-service-account
   namespace: {{ .Release.Namespace }}
roleRef:
    kind: Role
    name: redash-provisioner-role
    apiGroup: ""
---
apiVersion: v1
kind: ServiceAccount
metadata:
    name: redash-provisioner-service-account
    namespace: {{ .Release.Namespace }}