apiVersion: v1
kind: ServiceAccount
metadata:
    name: provisioning-redash
    namespace: {{ .Release.Namespace }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
    name: redash-provisioner
    namespace: {{ .Release.Namespace }}
rules:
    - apiGroups: [""]
      resources:
        - pods