{{- $RedashEmail := .Values.archive.redashEmail | required ".Values.archive.redashEmail is required." -}}
{{- $RedashPass := .Values.archive.redashPassword | required ".Values.archive.redashPassword is required." -}}
---
apiVersion: v1
kind: Secret
metadata:
    name: postgresql-secret
    namespace: {{ .Release.Namespace }}
type: Opaque 
data:
    user: {{ $RedashEmail | b64enc | quote }}
    password: {{ $RedashPass | b64enc | quote }}