apiVersion: v1
kind: Secret
metadata:
    name: postgresql-secret
    namespace: {{ .Release.Namespace }}
type: Opaque 
data:
    user: {{ .Values.database.pgUser | b64enc | quote }}
    password: {{ .Values.database.pgPass | b64enc | quote }}